/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.ContaCorrente;
import entidade.Movimentacao;
import entidade.Pessoa;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import negocio.NContaCorrente;
import negocio.NMovimentacao;
import negocio.NPessoa;
import padrao.Deposito;
import padrao.Saque;
import persistencia.PPessoaConta;

/**
 *
 * @author luisf
 */
public class TelaAutoAtendimento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAutoAtendimento
     */
    private NPessoa nPessoa = new NPessoa();
    private final Pessoa pessoa;
    private PPessoaConta pPessoaConta;
    private int op = 0;
    private ContaCorrente contaAtual;
    private DecimalFormat df = new DecimalFormat("#0.00");

    public TelaAutoAtendimento() throws SQLException {
        this.pessoa = nPessoa.consultar(Login.getPessoa().getId());
        initComponents();
        buscarDados();
        setarInvisivel();
        jButtonExecutar.setEnabled(false);
    }

    private void buscarDados() {
        try {
            jLabelCliente.setText(pessoa.getNome());
            for (ContaCorrente cc : new NContaCorrente().listar()) {
                pPessoaConta = new PPessoaConta();
                if (pPessoaConta.consultar(cc.getConta().getId()).getId_pessoa() == pessoa.getId()) {
                    jComboBoxContaSaq.addItem(cc.getConta().getNumero());
                    contaAtual = cc;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCliente = new javax.swing.JLabel();
        jPanelOPS = new javax.swing.JPanel();
        jLabelOP = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelSenha = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldConta = new javax.swing.JTextField();
        jLabelContaDep = new javax.swing.JLabel();
        jLabelAgencia = new javax.swing.JLabel();
        jTextFieldAgencia = new javax.swing.JTextField();
        jComboBoxContaSaq = new javax.swing.JComboBox<>();
        jLabelContaSaq = new javax.swing.JLabel();
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultado = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButtonSaldo = new javax.swing.JButton();
        jButtonSaque = new javax.swing.JButton();
        jLabelOperacao = new javax.swing.JLabel();
        jButtonDeposito = new javax.swing.JButton();
        jButtonExtrato = new javax.swing.JButton();
        jButtonExecutar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setTitle("Autoatendimento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jLabelCliente.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabelCliente.setText("Cliente");

        jPanelOPS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelOPS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelOP.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabelOP.setText("OP escolhida");
        jPanelOPS.add(jLabelOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jPasswordFieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelSenha.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabelSenha.setText("Senha:");

        jLabelValor.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabelValor.setText("Valor:");

        jTextFieldConta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelContaDep.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabelContaDep.setText("Conta:");

        jLabelAgencia.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabelAgencia.setText("Agência:");

        jTextFieldAgencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jComboBoxContaSaq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jLabelContaSaq.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabelContaSaq.setText("Conta:");

        jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jFormattedTextFieldValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldValor.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFormattedTextFieldValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelContaDep)
                    .addComponent(jLabelAgencia)
                    .addComponent(jLabelContaSaq)
                    .addComponent(jLabelSenha)
                    .addComponent(jLabelValor))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxContaSaq, 0, 97, Short.MAX_VALUE)
                    .addComponent(jTextFieldAgencia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldConta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordFieldSenha)
                    .addComponent(jFormattedTextFieldValor))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAgencia)
                    .addComponent(jTextFieldAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContaDep)
                    .addComponent(jTextFieldConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxContaSaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContaSaq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabelValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenha))
                .addContainerGap())
        );

        jPanelOPS.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 44, 190, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaResultado.setEditable(false);
        jTextAreaResultado.setColumns(20);
        jTextAreaResultado.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResultado);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 270, 194));

        jPanelOPS.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 13, 290, 216));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSaldo.setText("Saldo");
        jButtonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoActionPerformed(evt);
            }
        });

        jButtonSaque.setText("Saque");
        jButtonSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaqueActionPerformed(evt);
            }
        });

        jLabelOperacao.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabelOperacao.setText("Operação:");

        jButtonDeposito.setText("Depósito");
        jButtonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositoActionPerformed(evt);
            }
        });

        jButtonExtrato.setText("Extrato");
        jButtonExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelOperacao)
                    .addComponent(jButtonSaque)
                    .addComponent(jButtonDeposito)
                    .addComponent(jButtonSaldo)
                    .addComponent(jButtonExtrato))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOperacao)
                .addGap(18, 18, 18)
                .addComponent(jButtonSaque)
                .addGap(18, 18, 18)
                .addComponent(jButtonDeposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExtrato)
                .addGap(18, 18, 18)
                .addComponent(jButtonSaldo)
                .addGap(35, 35, 35))
        );

        jButtonExecutar.setText("Executar");
        jButtonExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanelOPS, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButtonExecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelOPS, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButtonVoltar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonExecutar)
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaqueActionPerformed
        try {
            op = 1;
            setarInvisivel();
            jLabelOP.setText("Saque");
            jComboBoxContaSaq.setVisible(true);
            jFormattedTextFieldValor.setVisible(true);
            jLabelContaSaq.setVisible(true);
            jComboBoxContaSaq.setVisible(true);
            jLabelValor.setVisible(true);
            jLabelSenha.setVisible(true);
            jPasswordFieldSenha.setVisible(true);
            jButtonExecutar.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaqueActionPerformed

    private void jButtonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositoActionPerformed
        try {
            op = 2;
            setarInvisivel();
            jLabelOP.setText("Depósito");
            jLabelAgencia.setVisible(true);
            jTextFieldAgencia.setVisible(true);
            jLabelContaDep.setVisible(true);
            jTextFieldConta.setVisible(true);
            jFormattedTextFieldValor.setVisible(true);
            jLabelValor.setVisible(true);
            jButtonExecutar.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonDepositoActionPerformed

    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarActionPerformed
        try {
            Double valorOP = Double.parseDouble(jFormattedTextFieldValor.getText());
            ContaCorrente contaDeposito = new NContaCorrente().consultarPorNumero(jTextFieldConta.getText());
            if (jComboBoxContaSaq.getSelectedIndex() == 0) {
                throw new Exception("Selecione a conta!");
            }
            switch (op) { 
                case 1:
                    if (jPasswordFieldSenha.getText().isEmpty()) {
                        throw new Exception("Informe a senha!");
                    }
                    if (jFormattedTextFieldValor.getText().isEmpty()) {
                        throw new Exception("Informe o valor da operação!");
                    }
                    Saque saque = new Saque();
                    //como passar essa validação para a camada de negócio?
                    if ((contaAtual.getConta().getSaldo()+contaAtual.getLimite()) - valorOP < 0) {
                        throw new Exception("Saldo insuficiente!");
                    } else {
                        saque.executarOperacao(contaAtual.getLimite(), contaAtual.getConta().getSaldo(),
                                valorOP, "saque", contaAtual.getConta().getNumero(),
                                pessoa.getId(), "senha...");
                        jTextAreaResultado.setText("Sacando.......................R$ " + df.format(valorOP) + "\n"
                                + "Saldo atual:..................R$ " + (contaAtual.getConta().getSaldo() - valorOP));
                        //necessário subtrair pois só atualiza o saldo depois que termina a operação
                    }
                    break;
                case 2:
                    if (jTextFieldAgencia.getText().isEmpty()) {
                        throw new Exception("Preencha o número da Agência!");
                    }
                    if (jTextFieldConta.getText().isEmpty()) {
                        throw new Exception("Preencha o número da Conta!");
                    }
                    if (jFormattedTextFieldValor.getText().isEmpty()) {
                        throw new Exception("Informe o valor da operação!");
                    }
                    Deposito deposito = new Deposito();
                    deposito.executarOperacao(contaDeposito.getLimite(), contaDeposito.getConta().getSaldo(),
                            valorOP, "saque", contaDeposito.getConta().getNumero(),
                            pessoa.getId(), "senha...");
                    jTextAreaResultado.setText("Depositando...................R$ " + df.format(valorOP) + "\n");
                    break;
                default:
                    break;
            }
            jButtonExecutar.setEnabled(false);
            setarInvisivel();
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Atenção!", 2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Atenção!", 2);
        }
    }//GEN-LAST:event_jButtonExecutarActionPerformed

    private void jButtonExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtratoActionPerformed
        try {
            String resultado = "";

            for (Movimentacao mov : new NMovimentacao().listar()) {
//                pPessoaConta = new PPessoaConta();
                if (mov.getId_conta() == contaAtual.getConta().getId()) {
                    resultado += "Data : " + mov.getData() + "\n"
                            + "Tipo : " + mov.getTipo() + "\n"
                            + "Valor: R$ " + df.format(mov.getValor()) + "\n"
                            + " ----------------------- \n";
                }
            }
            jTextAreaResultado.setText(resultado + "Saldo atual: R$ " + df.format(contaAtual.getConta().getSaldo())
                    + "\nLimite: R$ " + df.format(contaAtual.getLimite())
                    + "\nSaldo com limite: R$ " + df.format(contaAtual.getLimite() + contaAtual.getConta().getSaldo()));
            jButtonExecutar.setEnabled(false);
            setarInvisivel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Conta sem movimentação!", "Atenção!", 2);
        }
    }//GEN-LAST:event_jButtonExtratoActionPerformed

    private void jButtonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoActionPerformed
        try {
            jTextAreaResultado.setText("Saldo atual: R$ " + df.format(contaAtual.getConta().getSaldo())
                    + "\nLimite: R$ " + df.format(contaAtual.getLimite())
                    + "\nSaldo com limite: R$ " + df.format(contaAtual.getLimite() + contaAtual.getConta().getSaldo()));
            jButtonExecutar.setEnabled(false);
            setarInvisivel();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaldoActionPerformed

    private void setarInvisivel() {
        jLabelOP.setText("");
        jTextAreaResultado.setOpaque(true);
        jFormattedTextFieldValor.setVisible(false);
        jTextFieldAgencia.setVisible(false);
        jTextFieldConta.setVisible(false);
        jComboBoxContaSaq.setVisible(false);
        jPasswordFieldSenha.setVisible(false);
        jLabelAgencia.setVisible(false);
        jLabelContaSaq.setVisible(false);
        jLabelContaDep.setVisible(false);
        jLabelSenha.setVisible(false);
        jLabelValor.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeposito;
    private javax.swing.JButton jButtonExecutar;
    private javax.swing.JButton jButtonExtrato;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JButton jButtonSaque;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxContaSaq;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JLabel jLabelAgencia;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelContaDep;
    private javax.swing.JLabel jLabelContaSaq;
    private javax.swing.JLabel jLabelOP;
    private javax.swing.JLabel jLabelOperacao;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelOPS;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaResultado;
    private javax.swing.JTextField jTextFieldAgencia;
    private javax.swing.JTextField jTextFieldConta;
    // End of variables declaration//GEN-END:variables
}
