/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.Pessoa;
import entidade.TelaLogin;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author luisf
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        TelaLogin telaLogin = new TelaLogin(this);
        telaLogin.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        telaLogin.setVisible(true);
        verificarUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonAbreConta = new javax.swing.JButton();
        jButtonManutencao = new javax.swing.JButton();
        jButtonOperacoes = new javax.swing.JButton();
        jButtonCadastro = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jButtonATM = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Bancário Rico");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Dimension d2 = JDesktopPanePrincipal.getSize();
        jPanel1.setLocation((d2.width - jPanel1.getSize().width) / 2, (d2.height - jPanel1.getSize().height) / 2);
        jPanel1.setOpaque(false);

        jButtonAbreConta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAbreConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/044-banking.png"))); // NOI18N
        jButtonAbreConta.setText("Abertura de conta");
        jButtonAbreConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAbreConta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAbreConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbreContaActionPerformed(evt);
            }
        });

        jButtonManutencao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/007-cash-10.png"))); // NOI18N
        jButtonManutencao.setText("Manutenção");
        jButtonManutencao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonManutencao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManutencaoActionPerformed(evt);
            }
        });

        jButtonOperacoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOperacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/018-money-1.png"))); // NOI18N
        jButtonOperacoes.setText("Operações");
        jButtonOperacoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOperacoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperacoesActionPerformed(evt);
            }
        });

        jButtonCadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/055-archive.png"))); // NOI18N
        jButtonCadastro.setText("Cadastros");
        jButtonCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });

        jButtonRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/073-report-1.png"))); // NOI18N
        jButtonRelatorio.setText("Relatórios");
        jButtonRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });

        jButtonATM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonATM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/050-atm-5.png"))); // NOI18N
        jButtonATM.setText("Autoatendimento");
        jButtonATM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonATM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonATM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAbreConta)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRelatorio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonManutencao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonOperacoes)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastro)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonATM)))
                .addGap(68, 104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonCadastro, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonOperacoes))
                    .addComponent(jButtonATM))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAbreConta)
                    .addComponent(jButtonManutencao)
                    .addComponent(jButtonRelatorio))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("usuario");

        JDesktopPanePrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDesktopPanePrincipal.setLayer(jLabelUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JDesktopPanePrincipalLayout = new javax.swing.GroupLayout(JDesktopPanePrincipal);
        JDesktopPanePrincipal.setLayout(JDesktopPanePrincipalLayout);
        JDesktopPanePrincipalLayout.setHorizontalGroup(
            JDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDesktopPanePrincipalLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                .addComponent(jLabelUsuario)
                .addGap(175, 175, 175))
        );
        JDesktopPanePrincipalLayout.setVerticalGroup(
            JDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JDesktopPanePrincipalLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(JDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUsuario)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperacoesActionPerformed
        try {
            TelaOperacao telaOperacoes = new TelaOperacao();
            centralizarJInternalFrame(telaOperacoes);
            telaOperacoes.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonOperacoesActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        try {
            TelaCadastro telaCadastro = new TelaCadastro();
            centralizarJInternalFrame(telaCadastro);
            telaCadastro.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
        try {
            TelaRelatorio telaRelatorio = new TelaRelatorio();
            centralizarJInternalFrame(telaRelatorio);
            telaRelatorio.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    private void jButtonAbreContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbreContaActionPerformed
        try {
            TelaAbreConta telaAbreConta = new TelaAbreConta();
            centralizarJInternalFrame(telaAbreConta);
            telaAbreConta.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonAbreContaActionPerformed

    private void jButtonManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManutencaoActionPerformed
        try {
            TelaManutencao telaManutencao = new TelaManutencao();
            centralizarJInternalFrame(telaManutencao);
            telaManutencao.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonManutencaoActionPerformed

    private void jButtonATMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATMActionPerformed
        try {
            TelaAutoAtendimento telaAutoAtendimento = new TelaAutoAtendimento();
            centralizarJInternalFrame(telaAutoAtendimento);
            telaAutoAtendimento.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonATMActionPerformed

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        try {
            JOptionPane.showMessageDialog(rootPane, "Desenvolvido pelos alunos do Senai/Fatesg: \n\nDaniel Silva"
                    + "\nLetícia Ribeiro\nLuis Faria\n\nÍcones fornecidos por Freepik via"
                    + " Flaticon (www.flaticon.com)\n\nGoiânia - 2018", "Sobre", 2);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sistema Rico", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing
    
    private void centralizarJInternalFrame(JInternalFrame jInternalFrame) {
        Dimension d = JDesktopPanePrincipal.getSize();
        JDesktopPanePrincipal.add(jInternalFrame);
        jInternalFrame.setLocation((d.width - jInternalFrame.getSize().width) / 2, (d.height - jInternalFrame.getSize().height) / 2);
    }
    
    private void verificarUsuario() {
        Pessoa pessoa = Login.getPessoa();
        
        if (pessoa.getTipo_pessoa() == 1) {
            jButtonAbreConta.setEnabled(false);
            jButtonCadastro.setEnabled(false);
            jButtonManutencao.setEnabled(false);
            jButtonOperacoes.setEnabled(false);
            jButtonRelatorio.setEnabled(false);
        } else {
            jButtonATM.setEnabled(false);
        }
        jLabelUsuario.setText(pessoa.getNome());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktopPanePrincipal;
    private javax.swing.JButton jButtonATM;
    private javax.swing.JButton jButtonAbreConta;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonManutencao;
    private javax.swing.JButton jButtonOperacoes;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
